### PR TITLE
Separate installation scripts into production and development

### PR DESCRIPTION
**Pull request by za-arthur**
Installation scripts now can be combine from multiple files "_prod.sql", "_dev.sql". Only "_prod.sql" will be used if "IS_DEV" not passed.

To make installation script generation easier they are moved into "sql" folder. But because "sql" is already used by tests, test related files and folders were moved into "test" folder.

In addition to those changes docker related files are moved into "docker" folder.

### CODE REVIEW

**Comment by akorotkov** [comment]
> Installation scripts now can be combinite from multiple files "_1.sql", "_2.sql", ... . Only "_1.sql" will be used if "IS_DEV" not passed
> Move installation scripts into "sql" folder
> Move all tests into "test" folder

Could you please put these three steps into different commits?

**Comment by za-arthur** [comment]
@akorotkov thank you for looking into it. I made changes into separate commits.

**Comment by akorotkov** [comment]
Thank you. Now, this is much clearer and easier to review.
Suffixes `_1` and `_2` look like magic numbers. Should we use some words instead? Something like `_prod` and `_dev`, or `_basic` and `_debug`?

**Comment by za-arthur** [comment]
@akorotkov initially I also used `_prod.sql` and `_dev.sql` suffixes. But I changed it into numbers to be able to sort multiple files and to have order in which files are joined.
But I agree that numbers look a bit magic, I changed it to use `_prod.sql` and `_dev.sql` now.

**Comment by ImreSamu** [comment]
My Notes:
- I have no issue if this gets a higher priority than my complex PR. 
- However, before merging, it would be beneficial to also update `./doc/contributing/structure.mdx` .
- (maybe) Additionally, it might be a good idea to update `./test/README.md` and move it to `./test/test/README.md`.  ( but this is not critical ... )

Questions:
- Will the bash tools I currently use for testing ( `./ci/local_docker_matrix.sh` ; `./ci/docker_matrix.sh` ) be moved to the new `./test` directory in the future, or will they remain in their current location?  If yes ... then please add this information to the  `./doc/contributing/structure.mdx` .

**Comment by za-arthur** [comment]
> However, before merging, it would be beneficial to also update ./doc/contributing/structure.mdx .

Good point, I'll update it.

> (maybe) Additionally, it might be a good idea to update ./test/README.md and move it to ./test/test/README.md. ( but this is not critical ... )

Yep, I wasn't sure about this one. Do you know if it is possible to change the folder name `test/tests` to more clear name, for example `test/docker_tests`? I didn't find within the orioledb repo how it is referenced.

> Will the bash tools I currently use for testing ( ./ci/local_docker_matrix.sh ; ./ci/docker_matrix.sh ) be moved to the new ./test directory in the future, or will they remain in their current location? If yes ... then please add this information to the  ./doc/contributing/structure.mdx .

I think `ci` folder will stay same.

**Comment by za-arthur** [comment]
> Yep, I wasn't sure about this one. Do you know if it is possible to change the folder name test/tests to more clear name, for example test/docker_tests? I didn't find within the orioledb repo how it is referenced.

Alternatively I can move docker related files including tests into `./docker` folder.

**Comment by akorotkov** [comment]
> Alternatively I can move docker related files including tests into ./docker folder.

+1 for this option

**Comment by za-arthur** [comment]
- Updated `./doc/contributing/structure.mdx`
- Moved docker related files to the "docker" folder and updated relevant paths on scripts, GitHub workflows and documentation.

**Comment by akorotkov** [comment]
@ImreSamu, could you check if you're OK with changes?

**Comment by ImreSamu** [comment]
The changes seem fine to me.

It’s possible that I will suggest further refinements later regarding the ~ docker section, but these are not expected to affect others' work or introduce drastic modifications.

-----------------
Notes:

I tested two (non critical) programs I use :
* `./ci/local_docker_matrix.sh`   #  (  just one cycle ... )
* `./ci/docker_matrix.sh --base alpine:3.20 --pg-major 17 --compiler gcc`

and this modification needs to be applied now or later:

```bash
$ git diff
diff --git a/ci/docker_matrix.sh b/ci/docker_matrix.sh
index 36aa410..0993c3d 100755
--- a/ci/docker_matrix.sh
+++ b/ci/docker_matrix.sh
@@ -215,7 +215,7 @@ main() {
                         # Run Docker tests
                         execute_command "\"${OFFIMG_LOCAL_CLONE}/test/run.sh\" \
                             -c \"${OFFIMG_LOCAL_CLONE}/test/config.sh\" \
-                            -c \"test/orioledb-config.sh\" \"orioletest:${docker_tag}\" \
+                            -c \"docker/orioledb-config.sh\" \"orioletest:${docker_tag}\" \
                             2>&1 | \
                             tee \"${logpath}/${docker_tag}.test.log\""
 
diff --git a/ci/local_docker_matrix.sh b/ci/local_docker_matrix.sh
index f92d686..522c51f 100755
--- a/ci/local_docker_matrix.sh
+++ b/ci/local_docker_matrix.sh
@@ -62,9 +62,9 @@ for pg_major in "${pg_major_list[@]}" ; do
 
       # Determine the Dockerfile based on base OS
       if [ "$base_os" = "alpine" ]; then
-        dockerfile="Dockerfile"
+        dockerfile="docker/Dockerfile"
       elif [ "$base_os" = "ubuntu" ]; then
-        dockerfile="Dockerfile.ubuntu"
+        dockerfile="docker/Dockerfile.ubuntu"
       fi
 
       docker_tag="${pg_major}-${compiler}-${base_os}-${base_tag}"
@@ -82,7 +82,7 @@ for pg_major in "${pg_major_list[@]}" ; do
       # Run docker test : oriole + postgres official test scripts
       "${OFFIMG_LOCAL_CLONE}/test/run.sh" \
           -c "${OFFIMG_LOCAL_CLONE}/test/config.sh" \
-          -c "test/orioledb-config.sh" \
+          -c "docker/orioledb-config.sh" \
           "orioletest:${docker_tag}" 2>&1 | tee ${logpath}/"${docker_tag}".test.log
 
     done
```

**Comment by za-arthur** [comment]
@ImreSamu good catch! I missed those entries. I pushed the fix.

**Review by ImreSamu — APPROVED** [review]
The proposed changes look good,
and I don't see any critical issues that could cause problems.

**Comment by akorotkov** [comment]
@za-arthur, @ImreSamu, thank you!

**Pull request merged**
